import Foundation
import PromptlyKit
import PromptlyKitUtils

/// A service that suggests regular expression patterns by querying a language model.
public struct SuggestionService {
    private let coordinator: PrompterCoordinator

    public init(
        config: Config
    ) throws {
        coordinator = try PrompterCoordinator(config: config)
    }

    public func suggestPatterns(
        head: [String],
        tail: [String],
        truncatedSample: [String],
        toolName: String,
        toolDescription: String,
        arguments: JSONValue
    ) async throws -> [String] {
        let systemPrompt = buildSystemPrompt()
        let userPrompt = try buildUserPrompt(
            head: head,
            tail: tail,
            truncated: truncatedSample,
            toolName: toolName,
            toolDescription: toolDescription,
            arguments: arguments
        )

        let messages = [
            PromptMessage(role: .system, content: .text(systemPrompt)),
            PromptMessage(role: .user, content: .text(userPrompt))
        ]

        let result = try await coordinator.run(
            messages: messages,
            onEvent: { _ in }
        )

        guard let suggestion = result.finalAssistantText else {
            return []
        }

        return extractPatterns(from: suggestion)
    }

    private func buildSystemPrompt() -> String {
        """
        You are a tool that suggests up to five regular expressions in JSON array format to match important content in logs.

        Provide patterns based on the sample lines of the log.
        These will be used to extract relevant information from the truncated section.

        Example output:
        ```json
        [
            "ERROR.*",
            "WARNING.*"
        ]
        ```
        """
    }

    private func buildUserPrompt(
        head: [String],
        tail: [String],
        truncated: [String],
        toolName: String,
        toolDescription: String,
        arguments: JSONValue
    ) throws -> String {
        let headSample = head.joined(separator: "\n")
        let tailSample = tail.joined(separator: "\n")
        let truncatedSample = truncated.joined(separator: "\n")
        return """
        Leading samples:
        \(headSample)
        Trailing samples:
        \(tailSample)
        Truncated samples:
        \(truncatedSample)

        The log was generated by running command:
        name: \(toolName)
        description: \(toolDescription)

        The command was made with the following arguments:
        \(arguments)

        Please suggest up to five regular expressions in JSON array format that can be used to match important content in these logs.
        """
    }

    private func extractPatterns(from suggestion: String) -> [String] {
        guard
            let data = suggestion.data(using: .utf8),
            let patterns = try? JSONDecoder().decode([String].self, from: data)
        else {
            return []
        }

        return patterns
    }
}
